### ISSUE TITLE
Documentation on README file incorrect

### ISSUE THREAD

**Issue by vizio360** [NiklasPor/nx-remotecache-azure#12]
I just noticed that on the read me file the name of the environment variables are incorrect. They are missing the `_` after `NX`.

e.g. this `NXCACHE_AZURE_CONNECTION_STRING` should be `NX_CACHE_AZURE_CONNECTION_STRING`, and same for all the others.

**Comment by NiklasPor** [comment]
Could it be that you're using a version below `3.0.0` there was a breaking change were variables were renamed:

https://github.com/NiklasPor/nx-remotecache-azure/blob/main/CHANGELOG.md#300

**Comment by vizio360** [comment]
Yeap you are right, sorry I just saw v2.0.0 on the main page here on this repo 
![image](https://user-images.githubusercontent.com/138939/220855562-b542344f-98e3-45fd-866f-f70f84b88f2d.png)
and assumed that was the latest version, my bad.
