### ISSUE TITLE
Support for default credentials

### ISSUE THREAD

**Issue by mruoss** [NiklasPor/nx-remotecache-azure#15]
Hey there

Are there plans to support default credentials? We're using this lib in a CI pipeline where we authenticate using [OpenID Connect](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure). It would be nice to get support for this somehow.

pseudo:

```ts
import { DefaultAzureCredential } from '@azure/identity';

const fullUrl = 'https://some-account.blob.core.windows.net/...'
new BlockBlobClient(fullUrl, new DefaultAzureCredential());
```

**Comment by NiklasPor** [comment]
Available starting with `4.2.0` 👍
