### ISSUE TITLE
Missing license info

### ISSUE THREAD

**Issue by daiscog** [NiklasPor/nx-remotecache-azure#17]
This repo doesn't have a `LICENSE` file, but I notice the distributed `nx-remotecache-azure` and `nx-remotecache-custom` npm packages do contain `"license": "MIT"` in their package.json files.

Please could you add an explicit `LICENSE` file to both repos and the distributed packages to confirm that the work is indeed MIT-licensed?

**Comment by NiklasPor** [comment]
Sure, I'll add one right ahead

**Comment by NiklasPor** [comment]
I added an appropriate MIT license in all connected repos, thanks! 👍
