### ISSUE TITLE
feat: bump @azure/identity to v4

### ISSUE THREAD

**Issue by dmitry-stepanenko** [NiklasPor/nx-remotecache-azure#19]
`@azure/identity@4.0.0` has recently been released with a support for node v20. This package should take it into account. I can create a PR if you're ok with it @NiklasPor

**Comment by NiklasPor** [comment]
Ah awesome, I'm just about to release a new verison. I'll bumpt it 👍

**Comment by NiklasPor** [comment]
Bumped in `17.0.0`.
