### ISSUE TITLE
NX 19 peer dependency

### ISSUE THREAD

**Issue by EelcoLos** [NiklasPor/nx-remotecache-azure#23]
NX 19 released yesterday. I checked this morning and there is ap eer dependency with NX.
When using `ncu --peer` I see 
> Ignored incompatible updates (peer dependencies):
>  nx      18.3.4  →  19.0.0  reason: nx-remotecache-azure requires ^18.0.0

Can you release a version compatible with nx v19 please?

when installing nx 19 i get
> npm WARN Found: nx@18.3.4
npm WARN node_modules/nx
npm WARN   dev nx@"19.0.0" from the root project
npm WARN   8 more (@angular-eslint/builder, @angular-eslint/schematics, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer nx@"^18.0.0" from nx-remotecache-azure@18.0.0
npm WARN node_modules/nx-remotecache-azure
npm WARN   dev nx-remotecache-azure@"^18.0.0" from the root project
npm WARN ERESOLVE overriding peer dependency

but after, when trying `npm dedup` or `npm install again`:
> npm ERR! While resolving: nx-remotecache-azure@18.0.0
npm ERR! Found: nx@19.0.0
npm ERR! node_modules/nx
npm ERR!   dev nx@"19.0.0" from the root project
npm ERR!   nx@"19.0.0" from @nrwl/tao@19.0.0
npm ERR!   node_modules/@nrwl/tao
npm ERR!     @nrwl/tao@"19.0.0" from nx@19.0.0
npm ERR!   2 more (@nx/devkit, @nx/workspace)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer nx@"^18.0.0" from nx-remotecache-azure@18.0.0
npm ERR! node_modules/nx-remotecache-azure
npm ERR!   dev nx-remotecache-azure@"^18.0.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: nx@18.3.4
npm ERR! node_modules/nx
npm ERR!   peer nx@"^18.0.0" from nx-remotecache-azure@18.0.0
npm ERR!   node_modules/nx-remotecache-azure
npm ERR!     dev nx-remotecache-azure@"^18.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by NiklasPor** [comment]
Sure, shouldn't be an issue if there weren't any breaking changes to the cache API.

**Comment by EelcoLos** [comment]
> Sure, shouldn't be an issue if there weren't any breaking changes to the cache API.

are there any breaking changes?

**Comment by NiklasPor** [comment]
@EelcoLos I just published `nx-remotecache-azure@19.0.0` 📦

If you have any trouble with the release, feel free to open a new issue.
