### ISSUE TITLE
Request: Upgrade to NX 20

### ISSUE THREAD

**Issue by Sebastian-G** [NiklasPor/nx-remotecache-azure#26]
Hi 👋 , is it possible to upgrade to NX v20 soon?

**Comment by NiklasPor** [comment]
Yes, shouldn't be a problem

**Comment by code-by-gijs** [comment]
> Yes, shouldn't be a problem

when? 😁

**Comment by NiklasPor** [comment]
My phone battery blew up including my authenticator and I was on vacation last week and I'm on a work trip this week. So probably next week.

**Comment by NiklasPor** [comment]
`nx-remotecache-azure@20.0.0` is now published. Thanks for your patience 😁
