### ISSUE TITLE
Add Dotfile / .env Support

### ISSUE THREAD

**Issue by jogelin** [NiklasPor/nx-remotecache-azure#3]
Hello,

First of all, thanks a lot for this library, it is useful.

However, I would like to configure the access token correctly for my CI and the local developers.

For the CI, it is easy, just add the global variable.

But for local developers, I would like to setup a `.env` file with the key locally. 
But after some investigations, it seems that the `.env` is not read before the `tasksRunnerOptions`, is that right?
So how can I configure these variables correctly in local environments?

Then I was thinking, **"How Nx is doing with Nx cloud"**? [But it seems there approach is more to put the key in the `nx.conf` directly](https://nx.app/docs/manage-access)....but IMO this is dangerous.

Do you think it could be good that you are reading the `.env` at your level if it is not supported by Nx directly?

I had another reflection, is your library compatible with the RBAC system of azure?

Thank in advance ;)

**Comment by NiklasPor** [comment]
Dotfile support seems like a good idea, I'll add it soon in a merge request 🚀 

Regarding RBAC, yes it should work – the package is just using the blob storage API. If the token has the correct role it should be possible. I think you can read into it here: https://docs.microsoft.com/en-us/azure/storage/blobs/assign-azure-role-data-access?tabs=portal

**Comment by NiklasPor** [comment]
Should be added in `nx-remotecache-azure@1.0.0` 👍
