### ISSUE TITLE
Cannot find module 'stream/promises' with Node 14

### ISSUE THREAD

**Issue by GYatesIII** [NiklasPor/nx-remotecache-azure#6]
OS: Windows
node version: 14.18.1
nx version: 14.4.2
nx-remotecache-azure version: 2.0.0

Clean install, when I run any nx command, I'm greeted with the title error.

```
> NX  Cannot find module 'stream/promises'
```

Stack trace:
nx-remotecache-custom/create-remote-cache-retrieve.js
nx-remotecache-custom/create-custom-runner.js
nx-remotecache-custom/index.js
nx-remotecache-azure/index.js
...

I downgraded to try and v1.1.0 works as advertised. Thanks for this lib, and the remotecache-custom lib! Let me know if you need more info or how I can help.

**Comment by NiklasPor** [comment]
Hey @GYatesIII, my pleasure 😄 

So, it seems like I used the `stream/promises` API inside `nx-remotecache-custom`, which is only available after Node 16:
![image](https://user-images.githubusercontent.com/13211347/186905889-9ec5e81d-2007-4bb6-a427-598ad4fd38b5.png)

I'll try to fix this soon, but I won't get to it right away. If you can, **I'd strongly suggest you to upgrade to 16** as you'll have to do it in 2023 anyway (NodeJS LTS table):
![image](https://user-images.githubusercontent.com/13211347/186906226-e51624fb-5372-421b-97b2-1361e5c1a1c0.png)

Thanks for reporting 👍

**Comment by NiklasPor** [comment]
I don't think I'll add support before Node 14 runs out of the maintenance state. I suggest anyone to consider upgrading heavily.
