### ISSUE TITLE
The Env variables are packed into the JS bundle

### ISSUE THREAD

**Issue by haven2world** [NiklasPor/nx-remotecache-azure#7]
This plugin is using some environment variables to get azure account related info with the prefix "NX_".
But at the same time, the nx react plugin will inject environment variables with the same prefix into the code, and it will cause the credential leak.

**Comment by haven2world** [comment]
#8 
I created a PR @NiklasPor  could you take a look?

**Comment by NiklasPor** [comment]
Fixed in `3.0.0` thanks for pointing this out 👏
